---
# The following resources where utilised to create the config file and naming schemes:
# https://developer.arm.com/documentation/101427/
# https://developer.arm.com/documentation/pjdoc466751330-9685/latest/
# https://developer.arm.com/tools-and-software/development-boards/neoverse-reference-design

Core:
  Simulation-Mode: outoforder
  Clock-Frequency: 1.8
  Fetch-Block-Size: 32
  Micro-Operations: True
  Vector-Length: 256
Process-Image:
  Heap-Size: 1073741824
  Stack-Size: 1048576
Register-Set:
  GeneralPurpose-Count: 96
  FloatingPoint/SVE-Count: 128
  Predicate-Count: 48
  Conditional-Count: 128
Pipeline-Widths:
  Commit: 4
  Dispatch-Rate: 2
  FrontEnd: 4
  LSQ-Completion: 2
Queue-Sizes:
  ROB: 256
  Load: 40
  Store: 24
Branch-Predictor:
  BTB-bitlength: 11
L1-Cache:
  Access-Latency: 4
  Exclusive: False
  Load-Bandwidth: 80
  Store-Bandwidth: 32
  Permitted-Requests-Per-Cycle: 3
  Permitted-Loads-Per-Cycle: 3
  Permitted-Stores-Per-Cycle: 1
Ports:
  0:
    Portname: BR_0
    Instruction-Support:
    - BRANCH
  1:
    Portname: BR_1
    Instruction-Support:
    - BRANCH
  2:
    Portname: INT_SINGLE_CYCLE_0
    Instruction-Support:
    - INT_SIMPLE_ARTH_NOSHIFT
    - INT_SIMPLE_LOGICAL_NOSHIFT
    - INT_SIMPLE_CMP
  3:
    Portname: INT_SINGLE_CYCLE_1
    Instruction-Support:
    - INT_SIMPLE_ARTH_NOSHIFT
    - INT_SIMPLE_LOGICAL_NOSHIFT
    - INT_SIMPLE_CMP
  4:
    Portname: INT_MULTI_CYCLE_0
    Instruction-Support:
    - INT
    - PREDICATE
  5:
    Portname: INT_MULTI_CYCLE_1
    Instruction-Support:
    - INT_ARTH
    - INT_SIMPLE_CMP
    - INT_SIMPLE_LOGICAL
    - INT_MUL
  6:
    Portname: FP_ASIMD_0
    Instruction-Support:
    - FP
    - STORE_DATA_FP
    - STORE_DATA_SVE
  7:
    Portname: FP_ASIMD_1
    Instruction-Support:
    - FP_SIMPLE_ARTH
    - FP_SIMPLE_LOGICAL
    - SCALAR_MUL
    - STORE_DATA_FP
    - STORE_DATA_SVE
    - VECTOR_CMP
  8:
    Portname: FP_ASIMD_2
    Instruction-Support:
    - FP_SIMPLE_ARTH
    - FP_SIMPLE_LOGICAL
    - SCALAR_CVT
    - SCALAR_MUL
    - SCALAR_DIV_OR_SQRT
    - VECTOR_CMP
    - VECTOR_CVT
    - VECTOR_MUL
    - VECTOR_DIV_OR_SQRT
  9:
    Portname: FP_ASIMD_3
    Instruction-Support:
    - FP_SIMPLE_ARTH
    - FP_SIMPLE_LOGICAL
    - SCALAR_MUL
    - VECTOR_CMP
  10:
    Portname: LOAD_STORE_0
    Instruction-Support:
    - LOAD
    - STORE_ADDRESS
  11:
    Portname: LOAD_STORE_1
    Instruction-Support:
    - LOAD
    - STORE_ADDRESS
  12:
    Portname: LOAD_2
    Instruction-Support:
    - LOAD
  13:
    Portname: STORE_DATA_0
    Instruction-Support:
    - STORE_DATA_INT
  14:
    Portname: STORE_DATA_1
    Instruction-Support:
    - STORE_DATA_INT
Reservation-Stations:
  0:
    Size: 20
    Ports:
    - FLA
    - PR
    - EXA
  1:
    Size: 20
    Ports:
    - FLB
    - EXB
  2:
    Size: 10
    Ports:
    - EAGA
  3:
    Size: 10
    Ports:
    - EAGB
  4:
    Size: 19
    Ports:
    - BR
Execution-Units:
  0:
    Pipelined: True
    Blocking-Groups:
    - INT_DIV_OR_SQRT
    - FP_DIV_OR_SQRT
    - SVE_DIV_OR_SQRT
  1:
    Pipelined: True
    Blocking-Groups: 
    - INT_DIV_OR_SQRT
    - FP_DIV_OR_SQRT
    - SVE_DIV_OR_SQRT
  2:
    Pipelined: True
    Blocking-Groups: 
    - INT_DIV_OR_SQRT
    - FP_DIV_OR_SQRT
    - SVE_DIV_OR_SQRT
  3:
    Pipelined: True
    Blocking-Groups: 
    - INT_DIV_OR_SQRT
    - FP_DIV_OR_SQRT
    - SVE_DIV_OR_SQRT
  4:
    Pipelined: True
    Blocking-Groups: 
    - INT_DIV_OR_SQRT
    - FP_DIV_OR_SQRT
    - SVE_DIV_OR_SQRT
  5:
    Pipelined: True
    Blocking-Groups: 
    - INT_DIV_OR_SQRT
    - FP_DIV_OR_SQRT
    - SVE_DIV_OR_SQRT
  6:
    Pipelined: True
    Blocking-Groups: 
    - INT_DIV_OR_SQRT
    - FP_DIV_OR_SQRT
    - SVE_DIV_OR_SQRT
  7:
    Pipelined: True
    Blocking-Groups: 
    - INT_DIV_OR_SQRT
    - FP_DIV_OR_SQRT
    - SVE_DIV_OR_SQRT
Latencies:
  0:
    Instruction-Groups: 
    - INT
    Execution-Latency: 2
    Execution-Throughput: 1
  1:
    Instruction-Groups: 
    - INT_SIMPLE_ARTH_NOSHIFT
    - INT_SIMPLE_LOGICAL_NOSHIFT
    - INT_SIMPLE_CMP
    - INT_SIMPLE_CVT
    Execution-Latency: 1
    Execution-Throughput: 1
  2:
    Instruction-Groups: 
    - INT_MUL
    Execution-Latency: 5
    Execution-Throughput: 1
  3:
    Instruction-Groups: 
    - INT_DIV_OR_SQRT
    Execution-Latency: 12
    Execution-Throughput: 12
  4:
    Instruction-Groups: 
    - ~2910
    - ~4049
    Execution-Latency: 20
    Execution-Throughput: 20
  5:
    Instruction-Groups: 
    - FP_ARTH
    - FP_LOGICAL
    - FP_CMP
    Execution-Latency: 2
    Execution-Throughput: 1
  6:
    Instruction-Groups: 
    - SCALAR_CVT
    - SCALAR_MUL
    Execution-Latency: 3
    Execution-Throughput: 1
  7:
    Instruction-Groups: 
    - SCALAR_DV_OR_SQRT
    Execution-Latency: 7
    Execution-Throughput: 7
  8:
    Instruction-Groups: 
    - ~1195
    - ~1608
    Execution-Latency: 10
    Execution-Throughput: 10
  9:
    Instruction-Groups: 
    - ~1190
    - ~1606
    Execution-Latency: 15
    Execution-Throughput: 15
  10:
    Instruction-Groups: 
    - LOAD_SCALAR
    Execution-Latency: 2
    Execution-Throughput: 1
  11:
    Instruction-Groups: 
    - VECTOR_CVT
    - VECTOR_MUL
    - SVE_CVT
    - SVE_MUL
    Execution-Latency: 4
    Execution-Throughput: 1
  12:
    Instruction-Groups: 
    - VECTOR_DIV_OR_SQRT
    Execution-Latency: 7
    Execution-Throughput: 7
  13:
    Instruction-Groups: 
    - ~1199
    - ~1202
    - ~1612
    - ~1615
    - SVE_DIV_OR_SQRT
    Execution-Latency: 10
    Execution-Throughput: 10
  14:
    Instruction-Groups: 
    - ~1193
    - ~1203
    - ~1610
    - ~1616
    Execution-Latency: 13
    Execution-Throughput: 13
  15:
    Instruction-Groups: 
    - ~1192
    - ~1200
    - ~1609
    - ~1613
    Execution-Latency: 15
    Execution-Throughput: 15
  16:
    Instruction-Groups: 
    - LOAD_VECTOR
    - STORE_VECTOR
    - LOAD_SVE
    - STORE_SVE
    Execution-Latency: 2
    Execution-Throughput: 1
  17:
    Instruction-Groups: 
    - PREDICATE
    Execution-Latency: 3
    Execution-Throughput: 1
# CPU-Info mainly used to generate a replica of the special (or system) file directory 
# structure
CPU-Info:
  # Set Generate-Special-Dir to 'T' to generate the special files directory, or to 'F' to not.
  # (Not generating the special files directory may require the user to copy over files manually)
  Generate-Special-Dir: T
  # Core-Count MUST be 1 as multi-core is not supported at this time. (A64FX true value is 48)
  Core-Count: 1
  # Socket-Count MUST be 1 as multi-socket simulations are not supported at this time. (A64FX true value is 1)
  Socket-Count: 1
  # SMT MUST be 1 as Simultanious-Multi-Threading is not supported at this time. (A64FX true value is 1)
  SMT: 1
  # Below are the values needed to generate /proc/cpuinfo
  BogoMIPS: 200.00
  Features: fp asimd evtstrm sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm fcma dcpop sve
  CPU-Implementer: "0x46"
  CPU-Architecture: 8
  CPU-Variant: "0x1"
  CPU-Part: "0x001"
  CPU-Revision: 0
  # Package-Count is used to generate 
  # /sys/devices/system/cpu/cpu{0..Core-Count}/topology/{physical_package_id, core_id}
  Package-Count: 1