# The following resources where utilised to create the config file and naming schemes:
# https://en.wikichip.org/wiki/cavium/microarchitectures/vulcan

Core:
  ISA: AArch64
  Simulation-Mode: outoforder
  Clock-Frequency-GHz: 2.5
  Timer-Frequency-MHz: 200
  Micro-Operations: True
Fetch:
  Fetch-Block-Size: 128
  Loop-Buffer-Size: 64
  Loop-Detection-Threshold: 4
Process-Image:
  Heap-Size: 1073741824
  Stack-Size: 1048576
Register-Set:
  GeneralPurpose-Count: 154
  FloatingPoint/SVE-Count: 90
  Conditional-Count: 128
Pipeline-Widths:
  Commit: 8
  FrontEnd: 16
  LSQ-Completion: 3
Queue-Sizes:
  ROB: 320
  Load: 64
  Store: 36
Branch-Predictor:
  BTB-Tag-Bits: 11
  Saturating-Count-Bits: 2
  Global-History-Length: 10
  RAS-entries: 5
  Fallback-Static-Predictor: "Always-Taken"
L1-Data-Memory:
  Interface-Type: Fixed
L1-Instruction-Memory:
  Interface-Type: Flat
LSQ-L1-Interface:
  Access-Latency: 4
  Exclusive: False
  Load-Bandwidth: 32
  Store-Bandwidth: 16
  Permitted-Requests-Per-Cycle: 2
  Permitted-Loads-Per-Cycle: 2
  Permitted-Stores-Per-Cycle: 1
Ports:
  0:
    Portname: B0
    Instruction-Group-Support:
    - BRANCH
  1:
    Portname: B1
    Instruction-Group-Support:
    - BRANCH
  2:
    Portname: SX0
    Instruction-Group-Support:
    - INT
  3:
    Portname: SX1
    Instruction-Group-Support:
    - INT
  4:
    Portname: SX2
    Instruction-Group-Support:
    - INT
  5:
    Portname: SX3
    Instruction-Group-Support:
    - INT
  6:
    Portname: MX0
    Instruction-Group-Support:
    - INT
  7:
    Portname: MX1
    Instruction-Group-Support:
    - INT
  8:
    Portname: LS0
    Instruction-Group-Support:
    - LOAD
    - STORE_ADDRESS
  9:
    Portname: LS1
    Instruction-Group-Support:
    - LOAD
    - STORE_ADDRESS
  10:
    Portname: LD
    Instruction-Group-Support:
    - LOAD
  11:
    Portname: SD0
    Instruction-Group-Support:
    - STORE_DATA_INT
  12:
    Portname: SD1
    Instruction-Group-Support:
    - STORE_DATA_INT
  13:
    Portname: VX0
    Instruction-Group-Support:
    - FP
  14:
    Portname: VX1
    Instruction-Group-Support:
    - FP
  15:
    Portname: VX2
    Instruction-Group-Support:
    - FP
  16:
    Portname: VX3
    Instruction-Group-Support:
    - FP
Reservation-Stations:
  0:
    Size: 22
    Dispatch-Rate: 2
    Ports:
    - B0
    - SX0
  1:
    Size: 22
    Dispatch-Rate: 2
    Ports:
    - B1
    - SX1
  2:
    Size: 22
    Dispatch-Rate: 1
    Ports:
    - MX0
  3:
    Size: 22
    Dispatch-Rate: 1
    Ports:
    - MX1
  4:
    Size: 22
    Dispatch-Rate: 1
    Ports:
    - SX2
  5:
    Size: 22
    Dispatch-Rate: 1
    Ports:
    - SX3
  6:
    Size: 28
    Dispatch-Rate: 2
    Ports:
    - VX0
    - VX1
  7:
    Size: 28
    Dispatch-Rate: 2
    Ports:
    - VX2
    - VX3
  8:
    Size: 16
    Dispatch-Rate: 1
    Ports:
    - LS0
    - SD0
  9:
    Size: 16
    Dispatch-Rate: 1
    Ports:
    - LS1
    - SD1
  10:
    Size: 16
    Dispatch-Rate: 1
    Ports:
    - LD
Execution-Units:
  0:
    Pipelined: True
  1:
    Pipelined: True
  2:
    Pipelined: True
  3:
    Pipelined: True
  4:
    Pipelined: True
  5:
    Pipelined: True
  6:
    Pipelined: True
  7:
    Pipelined: True
  8:
    Pipelined: True
  9:
    Pipelined: True
  10:
    Pipelined: True
  11:
    Pipelined: True
  12:
    Pipelined: True
  13:
    Pipelined: True
  14:
    Pipelined: True
  15:
    Pipelined: True
  16:
    Pipelined: True
Latencies:
  0:
    Instruction-Groups: 
    - INT_SIMPLE_ARTH
    - INT_SIMPLE_LOGICAL
    Execution-Latency: 2
    Execution-Throughput: 2
  1:
    Instruction-Groups: 
    - INT_SIMPLE_ARTH_NOSHIFT
    - INT_SIMPLE_LOGICAL_NOSHIFT
    Execution-Latency: 1
    Execution-Throughput: 1
  2:
    Instruction-Groups: 
    - INT_MUL
    Execution-Latency: 5
    Execution-Throughput: 1
  3:
    Instruction-Groups: 
    - INT_DIV_OR_SQRT
    Execution-Latency: 39
    Execution-Throughput: 39
  4:
    Instruction-Groups: 
    - SCALAR_SIMPLE
    - SCALAR_MUL
    Execution-Latency: 6
    Execution-Throughput: 1
  5:
    Instruction-Groups: 
    - SCALAR_SIMPLE_CMP
    Execution-Latency: 5
    Execution-Throughput: 1
  6:
    Instruction-Groups: 
    - FP_SIMPLE_CVT
    Execution-Latency: 7
    Execution-Throughput: 1
  7:
    Instruction-Groups: 
    - FP_DIV_OR_SQRT
    Execution-Latency: 16
    Execution-Throughput: 16
  8:
    Instruction-Groups: 
    - VECTOR_SIMPLE
    - VECTOR_MUL
    Execution-Latency: 7
    Execution-Throughput: 1
  9:
    Instruction-Groups: 
    - SCALAR_SIMPLE_LOGICAL
    - SCALAR_SIMPLE_LOGICAL_NOSHIFT
    - VECTOR_SIMPLE_LOGICAL
    - VECTOR_SIMPLE_LOGICAL_NOSHIFT
    Execution-Latency: 1
    Execution-Throughput: 1
# CPU-Info mainly used to generate a replica of the special (or system) file directory 
# structure
CPU-Info:
  # Set Generate-Special-Dir to True to generate the special files directory, or to False to not.
  # (Not generating the special files directory may require the user to copy over files manually)
  Generate-Special-Dir: True
  # Core-Count MUST be 1 as multi-core is not supported at this time. (TX2 true value is 32)
  Core-Count: 1
  # Socket-Count MUST be 1 as multi-socket simulations are not supported at this time. (TX2 true value is 2)
  Socket-Count: 1
  # SMT MUST be 1 as Simultanious-Multi-Threading is not supported at this time. (TX2 true value is 4)
  SMT: 1
  # Below are the values needed to generate /proc/cpuinfo
  BogoMIPS: 2000.00
  Features: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 sve asimdfhm dit uscat ilrcpc flagm ssbs paca pacg dcpodp svei8mm svebf16 i8mm bf16 dgh rng
  CPU-Implementer: "0x41"
  CPU-Architecture: 8
  CPU-Variant: "0x1"
  CPU-Part: "0xd40"
  CPU-Revision: 1
  # Package-Count is used to generate 
  # /sys/devices/system/cpu/cpu{0..Core-Count}/topology/{physical_package_id, core_id}
  Package-Count: 1