name: clang format

on:
  workflow_call:
  workflow_dispatch:

jobs:
    clang_format:
      runs-on: ubuntu-latest
      name: clang format

      steps:

        - name: Install clang format
          run: |
            sudo apt-get update
            sudo apt-get upgrade
            sudo apt-get install -y clang-format

            clang-format --version

        - name: checkout
          uses: actions/checkout@v4

        - name: Apply clang format
          run: |
            SRC_LIST="$(find "./src" | grep -E ".*(\.cc$|\.hh$)")"
            TEST_LIST="$(find "./test" | grep -E ".*(\.cc$|\.hh$)")";
            sudo clang-format --verbose -i $SRC_LIST $TEST_LIST -style=file
        
        # push changes if clang-format did anything
        - name: Check for changes
          run: |
            if [[ `git status --porcelain` ]]; then
              echo "Code formatting issues found."
              git config --global user.name 'github-actions-clang-format'
              git config --global user.email 'github-actions[bot]@users.noreply.github.com'
              git commit -am "Applied clang-format"
              git push
            else
              echo "No code formatting issues."
            fi