name: Build_Test_SimEng
# description: Build and test simeng on various OS with various compilers followed by benchmarking and a peformance regression test followed by a clang format if all previous workflow succeed

on:
  push:
    # branches:
    #   - dev

jobs:
  # Job to run Reusable Workflow 1
  # LINUX_GCC_BUILD_TEST:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Linux + GCC checks
  #       uses: ./.github/workflows/LINUX_GCC_BUILD_TEST.yml
  #       with:
  #         secrets: ${{ secrets.SIMENGUOB_PAT }}

  # Job to run Reusable Workflow 2
  MACOS_GCC_BUILD_TEST:
    uses: UoB-HPC/SimEng/.github/workflows/MACOS_GCC_BUILD_TEST.yml@$GITHUB_REF_NAME
    secrets: inherit

  # # Job to run Reusable Workflow 3
  # call-workflow3:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run Reusable Workflow 3
  #       uses: your-org/your-repo/.github/workflows/workflow3.yml@main

  # # Job to run Reusable Workflow 4 after 1, 2, and 3
  # call-workflow4:
  #   runs-on: ubuntu-latest
  #   needs: 
  #     - call-workflow1
  #     - call-workflow2
  #     - call-workflow3
  #   steps:
  #     - name: Run Reusable Workflow 4
  #       uses: your-org/your-repo/.github/workflows/workflow4.yml@main
