name: Build_Test_SimEng
# description: Build and test simeng on various OS with various compilers followed by benchmarking and a peformance regression test followed by a clang format if all previous workflow succeed

on:
  push:
    # branches:
    #   - dev
  
jobs:
  LINUX_GCC_BUILD_TEST:
    uses: ./.github/workflows/LINUX_GCC_BUILD_TEST.yml
    secrets: inherit

  MACOS_GCC_BUILD_TEST:
    uses: ./.github/workflows/MACOS_GCC_BUILD_TEST.yml
    secrets: inherit

  MACOS_CLANG_BUILD_TEST:
    uses: ./.github/workflows/MACOS_CLANG_BUILD_TEST.yml
    secrets: inherit

  PERFORMANCE_REGRESSION:
    uses: ./.github/workflows/PERFORMANCE_REGRESSION.yml
    secrets: inherit

  CLANG_FORMAT:
    needs: 
      - LINUX_GCC_BUILD_TEST
      - MACOS_GCC_BUILD_TEST
      - MACOS_CLANG_BUILD_TEST
      - PERFORMANCE_REGRESSION

    uses: ./.github/workflows/CLANG_FORMAT.yml
    secrets: inherit
