name: Build_Test_SimEng
# description: Build and test simeng on various OS with various compilers followed by benchmarking and a peformance regression test followed by a clang format if all previous workflow succeed

on:
  push:
    # branches:
    #   - dev
  
jobs:
  ###################################
  # Debug Mode
  ###################################
  DEBUG_LINUX_GCC_BUILD_TEST:
    uses: ./.github/workflows/LINUX_GCC_BUILD_TEST.yml
    with:
      SIMENG-MODE: Debug
    secrets: inherit

  DEBUG_MACOS_GCC_BUILD_TEST:
    uses: ./.github/workflows/MACOS_GCC_BUILD_TEST.yml
    with:
      SIMENG-MODE: Debug
    secrets: inherit

  DEBUG_MACOS_CLANG_BUILD_TEST:
    uses: ./.github/workflows/MACOS_CLANG_BUILD_TEST.yml
    with:
      SIMENG-MODE: Debug
    secrets: inherit

  ###################################
  # Release Mode
  ###################################
  RELEASE_LINUX_GCC_BUILD_TEST:
    uses: ./.github/workflows/LINUX_GCC_BUILD_TEST.yml
    with:
      SIMENG-MODE: Release
    secrets: inherit
  
  RELEASE_MACOS_GCC_BUILD_TEST:
    uses: ./.github/workflows/MACOS_GCC_BUILD_TEST.yml
    with:
      SIMENG-MODE: Release
    secrets: inherit

  RELEASE_MACOS_CLANG_BUILD_TEST:
    uses: ./.github/workflows/MACOS_CLANG_BUILD_TEST.yml
    with:
      SIMENG-MODE: Release
    secrets: inherit

  ###################################
  # Compare runtime with Previous run time
  ###################################
  PERFORMANCE_REGRESSION:
    uses: ./.github/workflows/PERFORMANCE_REGRESSION.yml
    secrets: inherit

  CLANG_FORMAT:
    needs: 
      - DEBUG_LINUX_GCC_BUILD_TEST
      - DEBUG_MACOS_GCC_BUILD_TEST
      - DEBUG_MACOS_CLANG_BUILD_TEST
      - RELEASE_LINUX_GCC_BUILD_TEST
      - RELEASE_MACOS_GCC_BUILD_TEST
      - RELEASE_MACOS_CLANG_BUILD_TEST
      - PERFORMANCE_REGRESSION

    uses: ./.github/workflows/CLANG_FORMAT.yml
    secrets: inherit

