name: Build_Test_SimEng
# description: Build and test simeng on various OS with various compilers followed by benchmarking and a performance regression test followed by a clang format if all previous workflow succeed

on:
#  workflow_call:
#  push:
#     branches:
#       - dev

  pull_request:
    branches:
      - dev
      - main
    
#  schedule:
#    - cron: '0 0 */6 * *'  # Runs every 6 days
  
jobs:

  ###################################
  # Debug Mode
  ###################################
  DEBUG_LINUX:
    uses: ./.github/workflows/LINUX_BUILD_TEST.yml
    with:
      RUNNER: ubuntu-latest
      SIMENG-MODE: Debug
    secrets: inherit

  DEBUG_MACOS:
    uses: ./.github/workflows/MACOS_BUILD_TEST.yml
    with:
      SIMENG-MODE: Debug
    secrets: inherit

  ###################################
  # Release Mode
  ###################################
  RELEASE_LINUX:
    uses: ./.github/workflows/LINUX_BUILD_TEST.yml
    with:
      RUNNER: ubuntu-latest
      SIMENG-MODE: Release
    secrets: inherit
  
  RELEASE_MACOS:
    uses: ./.github/workflows/MACOS_BUILD_TEST.yml
    with:
      SIMENG-MODE: Release
    secrets: inherit


