name: Build_Test_SimEng
# description: Build and test simeng on various OS with various compilers followed by benchmarking and a peformance regression test followed by a clang format if all previous workflow succeed

on:
  # workflow_call:
  push:
    # branches:
    #   - dev
    
  schedule:
    - cron: '0 0 */6 * *'  # Runs every 6 days
  
jobs:
  ###################################
  # Debug Mode
  ###################################
  # DEBUG_LINUX_GCC:
  #   uses: ./.github/workflows/LINUX_GCC_BUILD_TEST.yml
  #   with:
  #     SIMENG-MODE: Debug
  #   secrets: inherit

  # NOTE: currently doens't work
  # DEBUG_MACOS_GCC:
  #   uses: ./.github/workflows/MACOS_GCC_BUILD_TEST.yml
  #   with:
  #     SIMENG-MODE: Debug
  #   secrets: inherit

  # DEBUG_MACOS_CLANG:
  #   uses: ./.github/workflows/MACOS_CLANG_BUILD_TEST.yml
  #   with:
  #     SIMENG-MODE: Debug
  #   secrets: inherit

  ###################################
  # Release Mode
  ###################################
  # RELEASE_LINUX_GCC:
  #   uses: ./.github/workflows/LINUX_GCC_BUILD_TEST.yml
  #   with:
  #     SIMENG-MODE: Release
  #   secrets: inherit
  
  # RELEASE_MACOS_GCC:
  #   uses: ./.github/workflows/MACOS_GCC_BUILD_TEST.yml
  #   with:
  #     SIMENG-MODE: Release
  #   secrets: inherit

  # RELEASE_MACOS_CLANG:
  #   uses: ./.github/workflows/MACOS_CLANG_BUILD_TEST.yml
  #   with:
  #     SIMENG-MODE: Release
  #   secrets: inherit

  ###################################
  # Compare runtime with Previous run time
  ###################################
  PERFORMANCE_REGRESSION:
    # needs:
    #   - RELEASE_LINUX_GCC
      
    uses: ./.github/workflows/PERFORMANCE_REGRESSION.yml
    with:
      # Number of runs of current commit to average over to compare to previous average hard coded as env vars
      RUNS: 10

    secrets: inherit

  # CLANG_FORMAT:
  #   needs: 
  #     - DEBUG_LINUX_GCC
  #     # - DEBUG_MACOS_GCC
  #     - DEBUG_MACOS_CLANG
  #     - RELEASE_LINUX_GCC
  #     # - RELEASE_MACOS_GCC
  #     - RELEASE_MACOS_CLANG
  #     - PERFORMANCE_REGRESSION

  #   uses: ./.github/workflows/CLANG_FORMAT.yml
  #   secrets: inherit

