name: Build_Test_SimEng
# description: Build and test simeng on various OS with various compilers followed by benchmarking and a peformance regression test followed by a clang format if all previous workflow succeed

on:
  push:
    # branches:
    #   - dev
  
jobs:
  LINUX_GCC_BUILD_TEST:
    uses: ./.github/workflows/LINUX_GCC_BUILD_TEST.yml
    with:
      SIMENG-MODE: Release
    secrets: inherit

  MACOS_GCC_BUILD_TEST:
    uses: ./.github/workflows/MACOS_GCC_BUILD_TEST.yml
    with:
      SIMENG-MODE: Release
    secrets: inherit

  MACOS_CLANG_BUILD_TEST:
    uses: ./.github/workflows/MACOS_CLANG_BUILD_TEST.yml
    with:
      SIMENG-MODE: Release
    secrets: inherit

  PERFORMANCE_REGRESSION:
    uses: ./.github/workflows/PERFORMANCE_REGRESSION.yml
    secrets: inherit
    
  RERUN-FAILED:
    runs-on: ubuntu-latest
    needs:
      - LINUX_GCC_BUILD_TEST
      - MACOS_GCC_BUILD_TEST
      - MACOS_CLANG_BUILD_TEST
      - PERFORMANCE_REGRESSION
      
    if: failure()
    steps:
      - name: Rerun failed jobs in the current workflow
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh run rerun ${{ github.run_id }} --failed

  CLANG_FORMAT:
    needs: 
      - LINUX_GCC_BUILD_TEST
      - MACOS_GCC_BUILD_TEST
      - MACOS_CLANG_BUILD_TEST
      - PERFORMANCE_REGRESSION
      - RERUN-FAILED

    uses: ./.github/workflows/CLANG_FORMAT.yml
    secrets: inherit

