name: PERFORMANCE_REGRESSION

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  BENCHMARK_BRANCH: 'make-file-build-system' # The branch inside the benchmark repo that has the script to run all benchmarks.
  PAT: ${{ secrets.SIMENGUOB_PAT }}

on:
  workflow_call:

jobs:
  Compare_Performances:
    runs-on: ubuntu-latest

    steps:
      #######################################
      # Clone SimEng fork
      #######################################
      - name: checkout v4
        uses: actions/checkout@v4
      
      - name: install deps
        shell: bash
        run: |
          sudo apt-get -y install bc
          sudo apt-get -y install gcc-10 g++-10 pip
      #######################################
      # Build SimEng without llvm or ninja
      #######################################
      - name: Build SimEng
        shell: bash
        run: |
          pip install pyparsing
          sudo cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DSIMENG_ENABLE_TESTS=ON -DSIMENG_OPTIMIZE=ON -DCMAKE_C_COMPILER=/usr/bin/gcc-10 -DCMAKE_CXX_COMPILER=/usr/bin/g++-10

          sudo cmake --build build -j $(nproc)

          sudo cmake --build build --target install

          echo "GCC_DIR=/usr/bin/gcc-10" >> $GITHUB_ENV
          echo "CPP_DIR=/usr/bin/g++-10" >> $GITHUB_ENV

      #######################################
      # Prints out info in isolated step for easy access.
      #######################################
      - name: INFO
        shell: bash
        run: |
          cat /etc/os-release 
          echo "_______________________________________"
          cmake --version
          echo "_______________________________________"
          "${{ env.GCC_DIR }}" --version
          which gcc
          echo "_______________________________________"
          "${{ env.CPP_DIR }}" --version
          which g++
          echo "_______________________________________"
          ls

      #######################################
      # Checkout simeng-benchmark repository
      #######################################
      - name: checking out benchmark repository
        uses: actions/checkout@v4
        with:
          repository: UoB-HPC/simeng-benchmarks
          ref: makefile-build-system
          token: ${{ env.PAT }}
          path: simeng-benchmarks

      #######################################
      # Cloverleaf
      #######################################
      - name: run cloverleaf benchmark
        uses: ./.github/actions/run_individual_benchmark
        with:
          benchmark_suite_name: 'CLOVERLEAF'
          benchmark_path: ./simeng-benchmarks/binaries/CloverLeaf/openmp/cloverleaf_gcc10.3.0_armv8.4+sve
          output_file: cloverleaf_benchmark_out.txt

      #######################################
      # miniBUDE
      #######################################
      - name: run miniBUDE benchmark
        uses: ./.github/actions/run_individual_benchmark
        with:
          benchmark_suite_name: 'MINIBUDE'
          benchmark_path: ./simeng-benchmarks/binaries/miniBUDE/openmp/minibude_gcc10.3.0_armv8.4+sve
          output_file: minibude_benchmark_out.txt
      #######################################
      # STREAM
      #######################################
      - name: run stream benchmark
        uses: ./.github/actions/run_individual_benchmark
        with:
          benchmark_suite_name: 'STREAM'
          benchmark_path: ./simeng-benchmarks/binaries/STREAM/stream_gcc10.3.0_armv8.4+sve
          output_file: stream_benchmark_out.txt
      #######################################
      # TeaLeaf
      #######################################
      - name: run TeaLeaf benchmark
        uses: ./.github/actions/run_individual_benchmark
        with:
          benchmark_suite_name: 'TEALEAF'
          benchmark_path: ./simeng-benchmarks/binaries/TeaLeaf/3d/tealeaf_gcc10.3.0_armv8.4+sve
          output_file: tealeaf_benchmark_out.txt
      
      
      #######################################
      # Delete Previous benchmark times and replace with new times
      #######################################
      - name: Delete previous benchmark time caches
        shell: bash
        run: |
          sudo mkdir -p -m 755 /etc/apt/keyrings \
          && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \

          sudo apt update && sudo apt install -y gh && sudo apt upgrade -y 
          gh extension install actions/gh-actions-cache

          caches=(
            cloverleaf_benchmark_out.txt
            minibude_benchmark_out.txt
            stream_benchmark_out.txt
            tealeaf_benchmark_out.txt
          )

          set +e
          echo "Deleting caches..."
          for cache in "${caches[@]}"; do
              gh actions-cache delete $cache --confirm
          done
          echo "Done"
        env: # environement variable scoped to this
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: store benchmark output into cache
        uses: actions/cache/save@v4
        with:
          path: ./cloverleaf_benchmark_out.txt
          key: cloverleaf_benchmark_out.txt
          
      - name: store benchmark output into cache
        uses: actions/cache/save@v4
        with:
          path: ./minibude_benchmark_out.txt
          key: minibude_benchmark_out.txt

      - name: store benchmark output into cache
        uses: actions/cache/save@v4
        with:
          path: ./stream_benchmark_out.txt
          key: stream_benchmark_out.txt

      - name: store benchmark output into cache
        uses: actions/cache/save@v4
        with:
          path: ./tealeaf_benchmark_out.txt
          key: tealeaf_benchmark_out.txt

      #######################################
      # Summary
      #######################################
      - name: Summary
        shell: bash
        run: |
          echo "#############################################"
          echo "CLOVERLEAF (cloverleaf_gcc10.3.0_armv8.4+sve)"
          echo "Current Time: $CLOVERLEAF_CURRENT_TIME"
          echo "Previous Time: $CLOVERLEAF_PREVIOUS_TIME"
          echo "Absolute Difference: $CLOVERLEAF_DIFFERENCE"
          
          echo "#############################################"
          echo "MINIBUDE (minibude_gcc10.3.0_armv8.4+sve)"
          echo "Current Time: $MINIBUDE_CURRENT_TIME"
          echo "Previous Time: $MINIBUDE_PREVIOUS_TIME"
          echo "Absolute Difference: $MINIBUDE_DIFFERENCE"

          echo "#############################################"
          echo "STREAM (stream_gcc10.3.0_armv8.4+sve)"
          echo "Current Time: $STREAM_CURRENT_TIME"
          echo "Previous Time: $STREAM_PREVIOUS_TIME"
          echo "Absolute Difference: $STREAM_DIFFERENCE"

          echo "#############################################"
          echo "TEALEAF (tealeaf_gcc10.3.0_armv8.4+sve)"
          echo "Current Time: $TEALEAF_CURRENT_TIME"
          echo "Previous Time: $TEALEAF_PREVIOUS_TIME"
          echo "Absolute Difference: $TEALEAF_DIFFERENCE"
      
      #######################################
      # Compare Results: 5% acceptance rate
      #######################################
      - if: ${{ always() }}
        name: Check CLOVERLEAF threshold
        run: |
          CLOVERLEAF_THRESHOLD=$(echo "scale=2; $CLOVERLEAF_PREVIOUS_TIME * 0.05" | bc)
          CLOVERLEAF_DIFF=$(echo "scale=2; $CLOVERLEAF_CURRENT_TIME - $CLOVERLEAF_PREVIOUS_TIME" | bc)
          CLOVERLEAF_ABS_DIFF=$(echo "if($CLOVERLEAF_DIFF < 0) -1*$CLOVERLEAF_DIFF else $CLOVERLEAF_DIFF" | bc)

          echo "+- CLOVERLEAF_THRESHOLD"

          if (( $(echo "$CLOVERLEAF_ABS_DIFF > $CLOVERLEAF_THRESHOLD" | bc -l) )); then
            echo "CLOVERLEAF time difference exceeds 5% threshold!"
            exit 1
          else
            echo "CLOVERLEAF runtime is within threshold of 5%!"
          fi
      
      - if: ${{ always() }}
        name: Check MINIBUDE threshold
        run: |
          MINIBUDE_THRESHOLD=$(echo "scale=2; $MINIBUDE_PREVIOUS_TIME * 0.05" | bc)
          MINIBUDE_DIFF=$(echo "scale=2; $MINIBUDE_CURRENT_TIME - $MINIBUDE_PREVIOUS_TIME" | bc)
          MINIBUDE_ABS_DIFF=$(echo "if($MINIBUDE_DIFF < 0) -1*$MINIBUDE_DIFF else $MINIBUDE_DIFF" | bc)

          echo "+- MINIBUDE_THRESHOLD"

          if (( $(echo "$MINIBUDE_ABS_DIFF > $MINIBUDE_THRESHOLD" | bc -l) )); then
            echo "MINIBUDE time difference exceeds 5% threshold!"
            exit 1
          else
            echo "MINIBUDE runtime is within threshold of 5%!"
          fi
      
      - if: ${{ always() }}
        name: Check STREAM threshold
        run: |
          STREAM_THRESHOLD=$(echo "scale=2; $STREAM_PREVIOUS_TIME * 0.05" | bc)
          STREAM_DIFF=$(echo "scale=2; $STREAM_CURRENT_TIME - $STREAM_PREVIOUS_TIME" | bc)
          STREAM_ABS_DIFF=$(echo "if($STREAM_DIFF < 0) -1*$STREAM_DIFF else $STREAM_DIFF" | bc)

          echo "+- STREAM_THRESHOLD"

          if (( $(echo "$STREAM_ABS_DIFF > $STREAM_THRESHOLD" | bc -l) )); then
            echo "STREAM time difference exceeds 5% threshold!"
            exit 1
          else
            echo "STREAM runtime is within threshold of 5%!"
          fi
      
      - if: ${{ always() }}
        name: Check TEALEAF threshold
        run: |
          TEALEAF_THRESHOLD=$(echo "scale=2; $TEALEAF_PREVIOUS_TIME * 0.05" | bc)
          TEALEAF_DIFF=$(echo "scale=2; $TEALEAF_CURRENT_TIME - $TEALEAF_PREVIOUS_TIME" | bc)
          TEALEAF_ABS_DIFF=$(echo "if($TEALEAF_DIFF < 0) -1*$TEALEAF_DIFF else $TEALEAF_DIFF" | bc)

          echo "+- TEALEAF_THRESHOLD"

          if (( $(echo "$TEALEAF_ABS_DIFF > $TEALEAF_THRESHOLD" | bc -l) )); then
            echo "TEALEAF time difference exceeds 5% threshold!"
            exit 1
          else
            echo "TEALEAF runtime is within threshold of 5%!"
          fi